# Source of list: https://gitstar-ranking.com/organizations

# Page 1

wget 'https://api.github.com/search/repositories?q=org:'{microsoft,google,ipfs,filecoin,facebook,apache,alibaba,vuejs,tensorflow,Tencent,github,freeCodeCamp,facebookresearch,fossasia,airbnb,symfony,dotnet,facebookarchive,angular,square,TheAlgorithms,vercel,mozilla,hashicorp,EbookFoundation,shadowsocks,kubernetes,rust-lang,twbs,Netflix,golang,apple,flutter,nodejs,elastic,spring-projects,laravel,aws,openai,electron,ant-design,JetBrains,Azure,NVIDIA,ReactiveX,ohmyzsh,spatie,h5bp,reduxjs,30-seconds,ethereum,pytorch,ossu,docker,GoogleCloudPlatform,thoughtbot,d3,Shopify,twitter,awslabs,doctrine,expressjs,ytdl-org,ElemeFE,huggingface,ionic-team,Automattic,Unity-Technologies,redis,Homebrew,doocs,rails,deepmind,tc39,grafana,gothinkster,FormidableLabs,denoland,reactjs,uber,apachecn,jquery,ansible,pallets,socketio,webpack,Yalantis,mapbox,spotify,GoogleChrome,mui,didi,atom,bilibili,jenkinsci,firebase,puppeteer,storybookjs,udacity,prometheus,moby,Ramotion}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 2

wget 'https://api.github.com/search/repositories?q=org:'{FortAwesome,OWASP,graphql,NVlabs,django,babel,fastai,cloudflare,opencv,keras-team,mongodb,Kong,python,bitcoin,home-assistant,segmentio,Genymobile,eclipse,akveo,getsentry,serverless,plotly,jgraph,codrops,nuxt,prettier,thephpleague,Semantic-Org,nestjs,OpnTec,gin-gonic,moment,signalapp,godotengine,gohugoio,pypa,realm,wix,gatsbyjs,IBM,ipfs,Kotlin,adobe,swagger-api,neovim,papers-we-love,chartjs,thunlp,netdata,linkedin,php-fig,postcss,encode,baidu,open-mmlab,jekyll,dcloudio,adafruit,Meituan-Dianping,Hack-with-Github,resume,lodash,pingcap,styled-components,HubSpot,mtdvio,koajs,oracle,TryGhost,dropbox,zsh-users,dmlc,PowerShell,angular-ui,strapi,scrapy,you-dont-need,tesseract-ocr,cypress-io,visionmedia,bytedance,yahoo,ValveSoftware,prisma,auth0,mobxjs,minio,scikit-learn,influxdata,rancher,raywenderlich,datawhalechina,w3c,syncthing,rstudio,meteor,caddyserver,marmelab,yarnpkg,x64dbg}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 3

wget 'https://api.github.com/search/repositories?q=org:'{traefik,discourse,openresty,twitter-archive,git,npm,realpython,JuliaLang,fex-team,mdn,ecomfe,composer,hoppscotch,webtorrent,tauri-apps,openstack,trailofbits,adobe-fonts,KhronosGroup,Leaflet,facebookincubator,videojs,infinitered,palantir,Alamofire,localstack,iview,gorilla,xitu,nytimes,pixijs,jupyter,basecamp,nccgroup,fastlane,gogs,containers,DefinitelyTyped,RocketChat,aspnet,nwjs,yeoman,hexojs,futurice,WordPress,tldr-pages,php,rapid7,metafizzy,guzzle,AFNetworking,gulpjs,heroku,Yelp,kriasoft,Qihoo360,frappe,filamentgroup,salesforce,parse-community,tastejs,nasa,powerline,clojure,impress,FreeCodeCampChina,rethinkdb,SnapKit,servo,pyenv,hyperledger,istio,huginn,sequelize,Polymer,xamarin,exacity,atlassian,Azure-Samples,bumptech,quilljs,getlantern,jitsi,allenai,pandas-dev,netlify,isocpp,SheetJS,codepath,raspberrypi,WebAssembly,ruby,bazelbuild,beego,standard,GitbookIO,googlecreativelab,AlloyTeam,sass,BVLCg}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 4

wget 'https://api.github.com/search/repositories?q=org:'{xmartlabs,SeleniumHQ,id-Software,ory,pinterest,request,mandiant,mastodon,open-guides,mybatis,docker-library,rollup,yiisoft,emberjs,confluentinc,XX-net,balderdashy,zalando,cockroachdb,algolia,nylas,phpDocumentor,usablica,PHPOffice,react-boilerplate,digitalocean,FFmpeg,netty,googlesamples,rabbitmq,NativeScript,vim,zxing,aliyun,paypal,quantopian,gruntjs,lewagon,geekcompany,openshift,certbot,processing,cli,ReactiveCocoa,jhipster,stripe,mitmproxy,browserify,cocos2d,mono,CocoaPods,tmux-plugins,zeromq,matplotlib,codemirror,kivy,PyCQA,vapor,aio-libs,instillai,ClickHouse,weaveworks,FriendsOfPHP,phoenixframework,ajaxorg,nats-io,naptha,elsewhencode,QSCTech,redox-os,gitlabhq,odoo,envoyproxy,OfficeDev,appium,select2,spring-cloud,dokku,libgdx,Modernizr,Jam3,electronicarts,celery,XiaoMi,transloadit,postmanlabs,Flipboard,bbc,Esri,dart-lang,coreos,slackhq,stanfordnlp,cheeriojs,naver,labstack,vmware,databricks,railsware,balena-io}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 5

wget 'https://api.github.com/search/repositories?q=org:'{learn-anything,parallax,icsharpcode,eslint,hapijs,roots,thx,tmux,harvesthq,react-bootstrap,hammerjs,ramda,zendesk,OAI,Khan,TypeStrong,sqlmapproject,trustedsec,cmderdev,react-component,mozilla-mobile,elixir-lang,arduino,ampproject,pugjs,CodeHubApp,ethz-asl,nektos,MostlyAdequate,hyperoslo,go-kit,NixOS,redux-saga,VundleVim,keystonejs,Reactive-Extensions,matomo-org,SwiftyJSON,sourcegraph,pytest-dev,scrapinghub,aosp-mirror,gofiber,matrix-org,VerbalExpressions,froala,strongloop,loklak,antlr,fluent,typelevel,etsy,matterport,requirejs,GetStream,datasciencemasters,ftlabs,hybridgroup,boostorg,ropensci,getredash,mochajs,avajs,CyanogenMod,swoole,numpy,nginx,scala,gliderlabs,AdguardTeam,reactnativecn,spring-attic,chromium,handsontable,cucumber,BabylonJS,gradle,ipython,localForage,sensepost,winstonjs,jupyterlab,tornadoweb,radareorg,zendframework,DataDog,zulip,android-cn,FallibleInc,openwrt,deezer,git-tips,wbkd,highlightjs,ShareX,forkingdog,amfe,css-modules,FasterXML,nodemailer}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 6

wget 'https://api.github.com/search/repositories?q=org:'{OptimalBits,puppetlabs,bitcoinbook,svg,jumpserver,uNetworking,Hacker0x01,fbsamples,crystal-lang,CreateJS,stretchr,osquery,libuv,js-cookie,FrontendMasters,playframework,zhihu,fullcalendar,rbenv,mpv-player,KnpLabs,akka,less,phonegap,yandex,Instagram,woocommerce,libgit2,TeamStuQ,haskell,fish-shell,lingochamp,telegramdesktop,locustio,bcit-ci,Masterminds,mailgun,dianping,NetEase,fivethirtyeight,cakephp,googlemaps,phusion,discord,googlefonts,fsprojects,openssl,toptal,h2oai,flarum,taosdata,pld-linux,uikit,jsdom,wekan,outline,PHPMailer,vim-airline,sbt,SpiderLabs,badges,interagent,GNOME,aseprite,twilio,appbaseio,cesanta,restic,nfl,travis-ci,scylladb,ceph,jasmine,bokeh,knownsec,dair-ai,node-red,exercism,mysqljs,chef,aurelia,textmate,qbittorrent,amazeui,SonarSource,micropython,nim-lang,joyent,shieldfy,StackExchange,EnterpriseQualityCoding,octokit,lyft,DevExpress,collectiveidea,esp8266,reactiveui,toml-lang,designmodo,i18next}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 7

wget 'https://api.github.com/search/repositories?q=org:'{xbmc,phacility,SAP,pouchdb,keycloak,sqlitebrowser,guardian,hyperium,wikimedia,libretro,karma-runner,statsd,owncloud,hubotio,dropzone,phalcon,wechaty,limetext,eBay,apiaryio,PerfectlySoft,bitnami,cisco,capistrano,pagekit,mockito,infernojs,kickstarter,fashiontec,dropwizard,source-foundry,adobe-webplatform,feathersjs,NLPchina,riot,getgrav,awsdocs,oxford-cs-deepnlp-2017,Xilinx,senchalabs,msgpack,bower,grab,IFTTT,CosmicMind,yabwe,primefaces,framer,avast,so-fancy,plasma-umass,cloudfoundry,LMAX-Exchange,reactphp,BishopFox,liriliri,intuit,asciinema,nette,slackapi,amzn,magento,99designs,go-redis,keybase,Carthage,basho,arangodb,boto,laracasts,sparkfun,cmusatyalab,nodeca,seatgeek,douban,sinatra,markdown-it,guardianproject,foreversd,dutchcoders,bitpay,allegro,qiniu,mutualmobile,PistonDevelopers,junit-team,bitly,slimphp,pillarjs,braziljs,llvm,torch,citusdata,ether,dogecoin,ziglang,OpenEmu,prestodb,greensock,codecentric}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 8

wget 'https://api.github.com/search/repositories?q=org:'{scotch-io,neo4j,exyte,getpelican,ServiceStack,cayleygraph,mkdocs,saltstack,venmo,keen,Quick,ckeditor,tinymce,guard,Moya,fmtlib,leanote,NUKnightLab,eclipse-vertx,IntelLabs,artsy,NVIDIAGameWorks,peers,node-inspector,reactioncommerce,gfx-rs,MithrilJS,docopt,aspnetboilerplate,BrowserSync,Intervention,haiwen,fabric,videolan,pili-engineering,jquery-archive,EsotericSoftware,wechat-miniprogram,CopyTranslator,18F,OpenVPN,MyCATApache,NodeBB,paperjs,spree,flatiron,uzh-rpg,diaspora,whatwg,googleworkspace,MiCode,jpush,krakenjs,mysql,frida,CachetHQ,ppy,revel,nginxinc,Kozea,ARM-software,activeadmin,progit,h2o,KeepSafe,boltdb,systemjs,vimeo,FreeCAD,coinbase,stylus,apereo,box,summernote,FriendsOfSymfony,selectize,gollum,badoo,vueuse,LightTable,jikexueyuanwiki,brix,willowtreeapps,CocoaLumberjack,linnovate,readthedocs,showdownjs,tumblr,couchbase,bytedeco,uxsolutions,RailsApps,FSecureLABS,cujojs,kubesphere,ruby-grape,AudioKit,objcio,SVProgressHUD,amfoss}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 9

wget 'https://api.github.com/search/repositories?q=org:'{wkhtmltopdf,pkg,erlang,UKPLab,systemd,spring-guides,reactor,nltk,voicerepublic,go-sql-driver,yhat,duckduckgo,Kitware,trailblazer,resque,Karumi,vipshop,OCA,Netflix-Skunkworks,polybar,automl,zaproxy,cyclejs,rspec,ajv-validator,watson-developer-cloud,howdyai,rubygems,StylishThemes,SFTtech,purescript,stylelint,pre-commit,LLK,OpenRA,flatlogic,tighten,memcached,softwaremill,openlayers,micro,gopherjs,dompdf,mathjax,zerotier,fantasyland,node-webot,youtube,evernote,rack,nodesource,Mantle,uutils,go-martini,reactos,browserstate,nomad,bpmn-io,koreader,fullstackio,CodeSeven,octobercms,kiegroup,tmuxinator,bufferapp,postgres,boot2docker,mozilla-services,CSAILVision,asciidoctor,nightwatchjs,dataarts,androidannotations,xiph,CppCon,linuxmint,dollarshaveclub,Financial-Times,vim-syntastic,ribot,the-control-group,mail-in-a-box,BoltsFramework,cytoscape,ocaml,openalpr,magicalpanda,real-logic,chocolatey,myclabs,webview,RisingStack,alicevision,10up,popcorn-official,HabitRPG,phpspec,trello,overleaf,networkx}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 10

wget 'https://api.github.com/search/repositories?q=org:'{lambci,sparklemotion,taigaio,cnodejs,OpenHFT,openhab,containrrr,path,App-vNext,cdnjs,restify,sockjs,vigetlabs,webcomponents,robotframework,Famous,eleme,httpie,coursera-dl,RestKit,knockout,ovh,twigphp,nanomsg,ffffffff0x,squizlabs,rails-api,fabric8io,alcatraz,alphagov,reactide,sendgrid,mailhog,SoftEtherVPN,purifycss,thecodingmachine,tildeio,forcedotcom,NaturalNode,hamcrest,vert-x3,pusher,Gallopsled,sdelements,git-up,sovereign,jquery-validation,sympy,openframeworks,EFForg,jshint,jOOQ,llvm-mirror,scipy,percona,freebsd,unity3d-jp,pittcsc,internetarchive,bloomberg,numenta,yui,deployphp,sinonjs,newrelic,yuantiku,HandBrake,Fody,zurb,ninenines,mesosphere,moonlight-stream,pymc-devs,umano,python-pillow,humanmade,Theano,CISOfy,thinkgem,snapappointments,probml,stfalcon-studio,MahApps,teamcapybara,ctfs,processone,zio,dingo,helmetjs,marionettejs,mirage,libimobiledevice,wordpress-mobile,varvet,pinax,AutoMapper,apidoc,sony,OnsenUI,pydata}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 11

wget 'https://api.github.com/search/repositories?q=org:'{swiftmailer,carrierwaveuploader,tutsplus,Rightpoint,SignalR,editorconfig,mailru,telerik,pockethub,numba,cosmos,typecho,bestiejs,enormego,graphite-project,Blizzard,amphp,tinode,gonum,bigbluebutton,ONLYOFFICE,FineUploader,mitre,bulletphysics,phpredis,Hammerspoon,braintree,codemix,webdriverio,oreillymedia,PyMySQL,lxc,chaijs,nsacyber,nmap,symless,emmetio,tuna,PrestaShop,cs231n,es-shims,splunk,cefsharp,c3js,spyder-ide,liferay,PaperMC,activerecord-hackery,mopidy,Sylius,thumbor,seajs,typekit,pyinstaller,react-toolbox,lightbend,imagemin,snowplow,Activiti,osxfuse,testdouble,mapeditor,camunda,greatscottgadgets,SecureAuthCorp,delight-im,voxpupuli,OpenRefine,glfw,poole,gitbucket,clips,medialize,brunch,SFML,walmartlabs,playcanvas,Laverna,node-modules,ARMmbed,sequelpro,blevesearch,qor,rkt,SublimeText,tweepy,fontello,MonoGame,PX4,AzureAD,OrchardCMS,weibocom,YOURLS,Nozbe,TTTAttributedLabel,VulcanJS,babun,stackgl,libevent,HIPS}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 12

wget 'https://api.github.com/search/repositories?q=org:'{citra-emu,maxmind,Pylons,Supervisor,puma,novoda,neo4j-contrib,prolificinteractive,mailpile,jwtk,soundcloud,HangfireIO,Workiva,almende,welldone-software,pry,Squirrel,FreeRDP,chatopera,versatica,seattlerb,mesos,HackerNews,zh-google-styleguide,dolphin-emu,deis,i3,moovweb,datastax,breach,minetest,man-group,mercari,broadinstitute,ssbc,openzfs,CartoDB,relax,flynn,sonata-project,crossbario,GSA,open-falcon,restsharp,instructure,mailchimp,pentaho,Level,Medium,SublimeLinter,stellar,CiscoDevNet,elementary,HospitalRun,sitepoint-editors,mediaelement,stacks-network,OmniSharp,HaxeFoundation,serilog,susiai,mindmup,kaminari,Cuberto,leancloud,eastlakeside,RT-Thread,draios,Behat,spring-io,WP-API,vaadin,middleman,hazelcast,Graylog2,Mango,keycastr,baidu-research,meilix,codecombat,sshuttle,wallabag,sumatrapdfreader,Vincit,hanami,Grouper,AdoptOpenJDK,mailcheck,TheOdinProject,tweag,cssinjs,assimp,cookpad,magit,puniverse,overtone,alipay,carlhuda,SeldonIO,googleads}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 13

wget 'https://api.github.com/search/repositories?q=org:'{hibernate,concourse,TrinityCore,bottlepy,sqlcipher,infinum,globocom,janestreet,stan-dev,clojure-emacs,shutterstock,g-truc,jshttp,unsplash,beautify-web,buzzfeed,letsencrypt,day8,openMVG,OctoPrint,HIT-SCIR,Tinkoff,PointCloudLibrary,centrifugal,hyperopt,greatfire,cmusphinx,git-for-windows,smartystreets,emacsorphanage,yixia,paramiko,KDAB,Samsung,IAIK,XVimProject,APSL,snap-stanford,NancyFx,HazyResearch,dc-js,emacs-tw,arachnys,component,usnistgov,zmap,openstreetmap,Compass,twisted,NetSPI,digitalbazaar,CodyHouse,Yubico,prerender,plantuml,nopSolutions,thu-ml,EasyDarwin,tabulapdf,mltframework,blue-yonder,cockpit-project,Kaggle,go-xorm,duplicati,MinecraftForge,sensiolabs,wercker,casperjs,Bearded-Hen,primus,Turfjs,taobao,statsmodels,WhiteHouse,jsfiddle,pyca,PixarAnimationStudios,vimwiki,VirusTotal,checkstyle,jsplumb,Sonarr,novus,lib,americanexpress,juju,silexphp,tryolabs,cran,wp-cli,phpmyadmin,ContainerSolutions,zotero,RayTracing,shoutem,BlackrockDigital,NervanaSystems,Codeception,qgis}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 14

wget 'https://api.github.com/search/repositories?q=org:'{QuantConnect,gocd,flyway,newsapps,umdjs,documentcloud,Comcast,fluentpython,tendermint,fail2ban,liip,Nepxion,MISP,propublica,googleanalytics,pubnub,musescore,couchbaselabs,qunarcorp,nelmio,ReactTraining,teslamotors,koding,jemalloc,micromata,morrisjs,Skyscanner,cython,jsonresume,json-api,Haneke,fruitcake,clibs,contentful,lampepfl,peco,sitespeedio,flightjs,fsnotify,viewflow,LLNL,okfn-brasil,wakatime,ternjs,WebKit,remoteinterview,zeroclipboard,lisa-lab,jsonmodel,hoaproject,joypixels,Respect,transmission,cloudtools,slim-template,microg,ember-cli,rangle,NodeOS,pimoroni,darktable-org,CleverRaven,devbridge,beanstalkd,flipkart-incubator,bup,LonamiWebs,tradingview,wpscanteam,gperftools,Ultimaker,Quartz,volatilityfoundation,Countly,btcsuite,codeforamerica,k9mail,rvm,illuminate,guardicore,sdc-alibaba,GaloisInc,metosin,meetecho,iron,openexchangerates,bitcoinjs,GameTechDev,languagetool-org,baconjs,ros,cnpm,ripple,PCSX2,gluster,racket,twitchtv,tictail,MacPass,blei-lab}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 15

wget 'https://api.github.com/search/repositories?q=org:'{ducksboard,faye,meganz,Freeboard,sensu,developmentseed,opencart,RobotsAndPencils,sandstorm-io,NorthwoodsSoftware,topojson,applidium,salesforce-ux,graphhopper,CatchChat,Mybridge,MiniProfiler,hprose,msys2,ACRA,ratchetphp,TechEmpower,WebDevStudios,getgauge,wxWidgets,openSUSE,spesmilo,flask-restful,lincolnloop,derbyjs,substance,open-source-parsers,fluent-ffmpeg,NanoHttpd,bookshelf,gitextensions,celluloid,snipsco,lostisland,at-import,jruby,NREL,PostgresApp,MTG,cmu-db,noodlewerk,ractivejs,jsdelivr,reagent-project,qemu,RustAudio,kif-framework,lutris,mapstruct,tus,ScottLogic,NLog,wallix,django-oscar,Roave,plumatic,conda,nestjsx,instacart,blockchain,xournalpp,inkle,LearnBoost,aws-cloudformation,pattern-lab,gcc-mirror,session-replay-tools,OpenDroneMap,openwisp,gocardless,iron-io,slap-editor,edwardtufte,oreilly-japan,cloudfoundry-attic,Aerolab,pocoproject,juxt,official-stockfish,bignerdranch,moxiecode,webpy,archlinux,launchbadge,gogo,bamlab,dlang,flot,angular-app,OpenTSDB,s3fs-fuse,cloudera,cocos,typelift,thi-ng}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 16

wget 'https://api.github.com/search/repositories?q=org:'{cplusplus,gatling,opf,agentejo,igniterealtime,robolectric,futurepress,AsyncHttpClient,iSECPartners,datasets,qt,openid,tum-vision,mautic,mamedev,arrow-kt,ros-planning,VKCOM,OSGeo,tsuru,webiny,opal,humhub,sparkle-project,zeek,FrictionalGames,LMMS,StackStorm,locationtech,card-io,devsisters,rustcc,springside,scalameta,for-GET,sublimehq,ruby-china,pfnet,python-visualization,JodaOrg,godaddy,orientechnologies,groupon,munki,gevent,networknt,esnet,DataScienceSpecialization,target,jscs-dev,MassTransit,cuckoosandbox,django-extensions,jbaysolutions,mycolorway,wso2,universal-ctags,storj,doorkeeper-gem,astropy,pressly,TeamHG-Memex,trivago,arrayfire,itext,popcorn-time,ros2,prose,egret-labs,brython-dev,720kb,adaltas,TeehanLax,hoodiehq,fastos,tools,mustache,mumble-voip,go-pg,ruby-concurrency,gocraft,ExactTarget,moq,jsfront,Juniper,kubeedge,syncfusion,amdjs,dangdangdotcom,500px,USArmyResearchLab,EventStore,JuliaStats,ThoughtWorksInc,Project-OSRM,binaryage,blackberry,go-yaml,PRML,IcaliaLabs}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 17

wget 'https://api.github.com/search/repositories?q=org:'{joomla,lua,SUSE,mojotech,thinkaurelius,TeamWin,LedgerHQ,journeyapps,bitstadium,jmespath,hootsuite,allure-framework,rolling-scopes,infobyte,getbem,eclipsesource,meanjs,disqus,logstash-plugins,jquery-ui-bootstrap,EverythingMe,openscad,bugsnag,MediaBrowser,Code52,missive,geocoder-php,tboox,agiliq,share,dotintent,syntaxhighlighter,thinkpixellab,north,pluralsight,vintasoftware,gephi,inloop,SteamDatabase,fontforge,Tapadoo,busyloop,gnuradio,MongoEngine,madebymany,hackclub,yapstudios,scikit-image,curlconverter,topcoat,suitcss,tecnickcom,Hexlet,fpinscala,locomotivemtl,componentjs,theforeman,vcr,CanvasPod,boxen,nodegit,WebGoat,tarantool,tidev,dialogflow,pritunl,DroidsOnRoids,HIT-Alibaba,imazen,adazzle,SparkPost,remind101,stitchfix,FastLED,evrone,particle-iot,whitesmith,clab,winjs,deployd,quickbirdstudios,Mojang,OpenKinect,Seeed-Studio,scalaz,atinfo,git-ftp,metabrainz,datacamp,phpseclib,red,Veil-Framework,mavlink,okfn,GarageGames,amplab,netguru,riemann,ctrlpvim,thoughtworks}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 18

wget 'https://api.github.com/search/repositories?q=org:'{noflo,rest-client,spring-projects-experimental,MacGapProject,openpgpjs,iconic,CanCanCommunity,idris-lang,rundeck,scala-js,shower,buildbot,fog,golang-china,teambition,spray,tableau,DATA-DOG,vavr-io,SublimeCodeIntel,assemble,Icinga,mruby,drapergem,pagarme,reworkcss,oddbird,urbit,Webschool-io,coin-or,Tribler,layervault,estools,fonoster,NuGet,leapmotion,swirldev,LWJGL,Linuxbrew,trezor,Flipkart,fox-it,quartznet,wit-ai,telly,phpbrew,unitedstates,halide,ledger,ZoneMinder,mirror,quartz-scheduler,bolt,akkadotnet,Strider-CD,serversideup,raml-org,TransitApp,widdix,CSSLint,fanout,camptocamp,wildbit,haml,vektra,Soundnode,replit,theintern,sysown,SVG-Edit,neuland,adjust,supercollider,TIBCOSoftware,mininet,SimformSolutionsPvtLtd,ankidroid,autofac,hashrocket,StockSharp,reactive-streams,mspnp,Kurento,elasticsearch-cn,Stratio,MariaDB,mqtt,jasperproject,refinery,ucb-bar,senecajs,UrbanApps,HumbleSoftware,funcool,unosquare,ansible-semaphore,DEAP,elves,Nike-Inc,ipython-contrib}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 19

wget 'https://api.github.com/search/repositories?q=org:'{nearform,prawnpdf,Dash-Industry-Forum,sdkman,inaka,grbl,openvenues,P0cL4bs,Facepunch,mapillary,grails,luvit,duilib,Varying-Vagrant-Vagrants,root-project,mlpack,sonatype,bugcrowd,twitterdev,twosigma,redmine,RubyMoney,jolicode,CouchPotato,Lemoncode,peerigon,linagora,skynetservices,pytoolz,studygolang,theonion,osrf,Brackeys,redecentralize,angular-translate,csscomb,Y2Z,thymeleaf,nprapps,quran,Studio-42,strukturag,qos-ch,web-animations,flant,IBM-Cloud,awesomeWM,NarrativeScience,sphinx-doc,Teradata,tangrams,Atmosphere,playgameservices,theleagueof,simplefocus,tianocore,hylang,jsbin,ANSSI-FR,probcomp,go-lang-plugin-org,roundcube,rackerlabs,ckan,SpongePowered,phpro,javaparser,23,cmus,plexinc,railsgirls,flowjs,appsquickly,TNG,tutao,fsharp,aasm,heremaps,LuaDist,Security-Onion-Solutions,es-analysis,swig,ring-clojure,unisonweb,nbs-system,pelias,freedomofpress,coteditor,rendrjs,forter,hak5,pfsense,Canner,libusb,NSHipster,litecoin-project,Bukkit,keepassx,dyweb,wildfly}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 20

wget 'https://api.github.com/search/repositories?q=org:'{CenturyLinkLabs,umbraco,blocks,ustwo,efficient,KJCracks,c9,tinkerpop,wireshark,observing,KiCad,crosswalk-project,1sters,seL4,buildkite,cs109,IronLanguages,mixpanel,imgix,Polidea,leanprover,InQuest,Codeinwp,zingchart,jspm,cuberite,ubuntu,yesodweb,ECSlidingViewController,netlify-templates,eventmachine,httpwg,bisq-network,goldendict,jquery-boilerplate,stacktracejs,pluginaweek,openstack-infra,codecov,RIOT-OS,cglib,mixi-inc,PHP-FFMpeg,bitcoinj,FreshRSS,Show-Me-the-Code,mapnik,montagejs,pegjs,dojo,UKHomeOffice,rubysherpas,sourcey,sleuthkit,ClusterHQ,CodeboxIDE,ioBroker,accord-net,cognitect-labs,datamade,varnish,pantsbuild,SciRuby,DistrictDataLabs,OpenTTD,cloudius-systems,dalibo,carrot,geopandas,smogon,GeneaLabs,robovm,mina-deploy,wesnoth,BlackArch,nowsecure,spine,cloudinary,OpenMW,jfrog,commonsense,errbit,biolab,phimpme,bevry,Q42,headjs,PaloAltoNetworks,jenv,mozilla-b2g,ros-industrial,zapier,HewlettPackard,reapp,education,drupal,DiUS,SVGKit,papyros,helios-framework}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 21

wget 'https://api.github.com/search/repositories?q=org:'{neutrinolabs,sciactive,snipcart,azavea,Jawbone,litl,numixproject,onelogin,goldmansachs,luggit,cartalyst,babylonhealth,MvvmCross,opserver,g0v,azkaban,citerus,collective,caelum,moodle,turbulenz,kiwi-bdd,EnterpriseDB,cfpb,veracrypt,liquibase,appacademy,crate,InterNations,ushahidi,interconnectit,kaltura,EngineHub,kakao,orchestral,melonjs,MobileChromeApps,springload,evilmartians,QuantEcon,xunit,statamic,redfin,panicinc,cvxgrp,ossec,introlab,zabbix,coq,Orange-OpenSource,ReactKit,dockerfile,scalanlp,timehop,SmartisanTech,WorldBrain,typhoeus,gocn,solus-project,WPO-Foundation,qTox,opencog,steelkiwi,MovingBlocks,mpdf,arduino-libraries,linuxdeepin,ms-iot,NebulousLabs,ngbp,stelligent,makinacorpus,Roblox,pmd,oblac,fastmonkeys,puphpet,lockfale,urho3d,RNCryptor,emacs-helm,CrowdStrike,nhibernate,lovoo,esl,UDST,espruino,osrg,calabash,appcoda,passbolt,spockframework,voormedia,analogdevicesinc,androguard,silverstripe,teamtnt,libigl,anijs,Guake}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 22

wget 'https://api.github.com/search/repositories?q=org:'{specta,DynamoRIO,ContinuumIO,nodejitsu,MoonHighway,shopware,ha,kennethreitz-archive,okta,node-ffi,nutzam,likeastore,ant-media,graalvm,HVF,SubtitleEdit,quarkslab,s3tools,bitovi,DeNA,querydsl,mootools,DockYard,mpc-hc,shunfei,skatejs,xoxco,Red5,relevance,spring-cloud-samples,wdas,roboguice,hatena,CrawlScript,pac4j,RedisLabs,padrino,Triple-T,socketstream,mgba-emu,webrtcHacks,ngageoint,tomahawk-player,touchlab,hypothesis,meteorhacks,the-tcpdump-group,Tivix,namshi,nodeschool,nunit,css,Frege,platzi,system76,siemens,Unidata,arkency,lexik,spree-contrib,atomicobject,supertuxkart,Doist,MozillaReality,comfy,uqfoundation,duojs,webmproject,bjango,goinaction,alura-cursos,broccolijs,lelylan,cognitect,grammarly,yahoojapan,gnea,pyinvoke,endgameinc,cake-build,robotmedia,pycontribs,gentoo,cozy,test-kitchen,linode,mogutt,edmodo,gitpython-developers,Stellarium,voxmedia,treasure-data,datorama,projectkudu,barbagroup,ravendb,npgsql,ThrowTheSwitch,ssllabs,gameplay3d}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 23

wget 'https://api.github.com/search/repositories?q=org:'{ChatSecure,ricochet-im,firehol,TheAmazingAudioEngine,OpenShot,qtile,pixelcog,VividCortex,mathnet,anjlab,uwdata,ARCANEDEV,madebysource,devkitPro,torproject,sketchplugins,visjs,touchstonejs,geopy,docpad,zeroturnaround,oclint,JSQLParser,functional-koans,deliciousbrains,sideeffects,actorapp,joblib,simplabs,CentOS,osmandapp,clientIO,warmcat,kikinteractive,welaika,machinalis,mirumee,kohana,a11yproject,twotoasters,saltstack-formulas,foursquare,nfc-tools,gree,LCTT,go-gomail,mirego,VBA-tools,python-excel,feedbin,tenable,renpy,peatio,web-standards-ru,pyrocms,codeclimate,BloombergMedia,Topshelf,Wisembly,zephir-lang,AxonFramework,fritzing,AnyChart,peek,prototypejs,auraphp,button,anchorcms,balanced,pmem,zostera,Ericsson,nodesecurity,Wizcorp,SelfControlApp,jboss-javassist,contiki-os,mljs,cvg,kni-labs,w3tecch,appjs,ubilabs,aerogear,rll,drone,rainmeter,nubank,thenativeweb,RobotLocomotion,enyojs,bsm,ninject,patternfly,Voog,fatfreecrm,TwilioDevEd,TwidereProject,CGAL,emacs-mirror}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 24

wget 'https://api.github.com/search/repositories?q=org:'{helium,Lora-net,voltrb,clementine-player,emitter-io,librenms,brick,SheffieldML,bosun-monitor,enthought,fusesource,Thinkmill,buildo,w3f,jwplayer,NCAR,xdebug,OpenBazaar,groovy,gophercon,Pixplicity,ThinkUpLLC,HoTT,geokit,thechangelog,xlwings,fail0verflow,cea-sec,rubysec,wal-e,opnsense,stormpath,jMonkeyEngine,Telefonica,zammad,yaml,akamai,mulesoft,cobrateam,FriendsOfCake,nerves-project,libyal,requests,MIT-LCP,envato,CSS-Tricks,tutumcloud,MultiMC,RDFLib,closeio,JuliaGPU,darkskyapp,WhatsApp,oroinc,jacoco,domoticz,FuzzyAutocomplete,agilebits,panda3d,looplab,fetlife,psycopg,javaee-samples,OLIMEX,Arachni,FontCustom,what-studio,hortonworks,AdaptiveConsulting,ActiveState,cocur,scijs,AltBeacon,idiap,TigerVNC,MailCore,magento-hackathon,hybridauth,chaplinjs,frictionlessdata,PowerDNS,engineyard,biopython,rubinius,Daemonite,intercom,lowRISC,addthis,craftyjs,plaid,frozenui,HdrHistogram,simpligility,python-openxml,agda,gss,flexxui,RedMadRobot,brownhci,SteamRE}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 25

wget 'https://api.github.com/search/repositories?q=org:'{SonyWWS,seomoz,firmata,kamon-io,mil-tokyo,Gamua,prooph,sketch-hq,ulule,mongoid,Dolibarr,screeps,area17,web-pal,vlfeat,picoe,tvbarthel,debops,optimizely,jpmml,undertow-io,then,spotbugs,boundary,MicroPyramid,skulpt,immutables,simplegeo,kimchi-project,gpac,easemob,salesagility,JaneaSystems,ros-perception,pilotmoon,beagleboard,taskrabbit,nicehash,o19s,stackshareio,USCiLab,Particular,HeidiSQL,quicksilver,processing-js,citation-style-language,omadahealth,ampache,sagemath,ElevenPaths,Entware,WiringPi,jetpacapp,EricssonResearch,ooyala,ArchiveTeam,presslabs,go-gl,JasperFx,geany,sjtug,cSploit,Alterplay,nickel-org,samtools,SmartThingsCommunity,IdeasOnCanvas,pythonnet,GNS3,http4s,giantswarm,sightmachine,scoutapp,play,KeenSoftwareHouse,smore-inc,upper,wecatch,ReturnInfinity,aurajs,LibreCAD,castleproject,hexchat,defold,datadesk,mozbrick,SublimeText-Markdown,ruby-amqp,Parsely,pimcore,OHDSI,postaljs,stablekernel,kissyteam,formly-js,opis,codegram,takari,platanus,overviewer}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 26

wget 'https://api.github.com/search/repositories?q=org:'{ghcjs,swcarpentry,FeralInteractive,cleanflight,react-native-training,Yoast,vanilla,Cue,scala-exercises,killbill,eth-sri,cn,exceptionless,Rdatatable,wolfSSL,emacs-china,savonrb,omnirom,scalatra,RolifyCommunity,appleple,bustle,clef,lastpass,kreait,Giphy,purescript-contrib,OpenRCE,latex3,swisnl,audiocogs,shoes,ipython-books,ros-drivers,salsify,pysal,sequenceiq,jeelabs,dobtco,fibjs,shogun-toolbox,rom-rb,pebble,dowjones,medialab,Parallels,coreutils,salsita,collectd,microweber,Codecademy,AOEpeople,fuel,rpm-software-management,opentk,PagerDuty,flitbit,DotNetAnalyzers,irssi,ghc,NLnetLabs,cs50,GumbyFramework,BendingSpoons,NordicPlayground,OISF,52inc,praw-dev,InsightSoftwareConsortium,spbooks,adobe-research,vispy,mysterioustrousers,sysdream,msysgit,divshot,oauth-io,greenelab,imgly,openbsd,CakeDC,openworm,pika,sunspot,gooselinux,SECFORCE,farbrausch,cappuccino,dssg,openvswitch,slick,go-ini,codelibs,alerta,locomotivecms,behave,mojolicious,igraph,wavedrom,JCTools}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 27

wget 'https://api.github.com/search/repositories?q=org:'{psecio,JabRef,sisl,openaddresses,dotless-de,torchbox,meituan,AstraZeneca,sysgears,django-compressor,bitrise-io,geoserver,biometrics,mangos,colour-science,wp-sync-db,munin-monitoring,BranchMetrics,Estimote,ponyorm,ModusCreateOrg,scipy-lectures,tmobile,ncbi,jamf,HubPress,emacsmirror,quil,Addepar,airlift,madebybowtie,makandra,pantheon-systems,alfajango,m-labs,snabbco,mit-nlp,mcneel,fpco,MozillaSecurity,rebuy-de,bitshares,DatabaseCleaner,pdfkit,crypto101,flycheck,jrsoftware,sparkbox,wp-premium,marbl,upyun,OData,spark-jobserver,Codiad,js-data,OrleansContrib,kandanapp,bittorrent,eggheadio,2amigos,sassoftware,hashie,echonest,osirislab,kartograph,aerospike,gpmgo,aubio,ethersphere,codeschool,CIRCL,trulia,Glimpse,remotestorage,provectus,libopencm3,Teevity,KumarRobotics,mixxxdj,oxyplot,team-supercharge,openannotation,code-troopers,bem,greenshot,propelorm,bcgit,osTicket,core-plot,postrank-labs,RobotiumTech,rocketeers,hellogcc,sendwithus,weechat,pyqtgraph,beardedspice,Spaceman-Labs,AtomicGameEngine,ua-parser}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 28

wget 'https://api.github.com/search/repositories?q=org:'{PMSI-AlignAlytics,opendns,rdio,sproutcore,linq2db,influitive,Payum,graphaware,actor-framework,petabridge,antitypical,smartstore,ezsystems,flame,spring,chukong,cerebris,BrentOzarULTD,wingify,synrc,QubitProducts,BootstrapCMS,aralejs,scaleway,railsbridge,Rajawali,opentok,objc-zen,pester,pushtorefresh,JuliaDiff,cloudfour,pedestal,web2py,lavabit,ManageIQ,2gis,vcmi,PGSSoft,OctopusDeploy,ImperialCollegeLondon,Bitmessage,minimagick,osmlab,hummingbird-me,shinydevelopment,Touchwonders,awesomemotive,dyne,Zomato,Sumi-Interactive,orangehill,tapquo,tagspaces,Praqma,Fewbytes,fcitx,wtforms,roo-rb,ashima,go-mgo,gocircuit,flickr,HackPlan,funny,FreeOpcUa,aol,jackaudio,opensourceBIM,recruit-mp,CosmosOS,toggl,makenotion,monix,inuitcss,redis-store,klarna,tooling,uploadcare,FStarLang,Factual,huaweicloud,savoirfairelinux,promises-aplus,UniSharp,mne-tools,uswitch,AtomLinter,Foliotek,leaningtech,redplanetlabs,SynoCommunity,LibreOffice,prey,shaarli,justeat,haskell-servant,mochi,AutoFixture,owntracks}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 29

wget 'https://api.github.com/search/repositories?q=org:'{cerner,livereload,octopress,hpcloud,intel-iot-devkit,pyload,MasteringOpenCV,translate,SOHU-Co,tent,nightscout,cybercog,rubyjs,BuzzFeedNews,Twitter4J,django-mptt,rebus-org,goraft,ruboto,elm-lang,ZupIT,gdg-x,nextflow-io,CloudCannon,boxcutter,acquia,pear,javamelody,orbitjs,immense,Reportr,agilie,inmite,GoogleWebComponents,pipelinedb,20tab,cloudfoundry-community,coduo,groveco,qmlbook,hyde,BitMEX,qossmic,checkr,mushorg,Asana,CorsixTH,PrincetonUniversity,uncomplicate,epam,Blosc,AppScale,openfoodfacts,mariadb-corporation,venomous0x,ChaiScript,gotgit,watir,Azoft,keymetrics,macoscope,OneGet,QubesOS,HaxeFlixel,ejoy,ClusterLabs,smart-on-fhir,hhvm,mongodb-labs,Clouda-team,teampoltergeist,love2d,scriptcs,huaban,Blockstream,researchgate,streamproc,lionheart,openfl,Ardour,thestk,TradeMe,omnigroup,PoshCode,Proxmark,premailer,bigcommerce,thefrontside,http-kit,sharetribe,readium,drush-ops,openseadragon,schematics,Alfresco,GIScience,plone,LavaLite,freeciv,hugeinc}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 30

wget 'https://api.github.com/search/repositories?q=org:'{galaxyproject,bootstrap-ruby,webprofusion,heiseonline,UnityTech,openfootball,Caliburn-Micro,helpers,Olivine-Labs,fooplugins,datatheorem,B-Sides,Mercateo,INRIA,getnikola,sonos,signalfx,codewars,dbpedia,everpix,quantmind,dahliaOS,webmodules,hmmlearn,mypaint,meltwater,neo4j-examples,inverse-inc,pydio,Ink,UB-Mannheim,reddit,strawlab,Hipo,mobify,sunscrapers,clojure-cookbook,devstructure,GPGTools,nipy,PingPlusPlus,libffi,ahkscript,xwp,autokey,arc90,PureDarwin,REhints,oortcloud,Wolox,modesttree,OPCFoundation,DragonBones,spatialaudio,netz98,alohaeditor,HipByte,newsdev,pixie-lang,scality,robotology,InteractiveAdvertisingBureau,ansistrano,adblockplus,nokia,tidalcycles,json-c,rtCamp,uxebu,keplerproject,melpa,rsmusllp,HappenApps,sipcapture,vifm,imapsync,AdRoll,pgmodeler,yourlabs,Mellanox,umeng,html5rocks,ctxis,rollbar,chipsec,ideo,cobbler,operasoftware,ModuleLoader,myriadrf,turtl,clojurewerkz,CopernicaMarketingSoftware,aspnet-contrib,play-co,etalab,edn-format,wallabyjs,okTurtles,Apipie}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 31

wget 'https://api.github.com/search/repositories?q=org:'{monome,autopkg,Gnucash,microcosm-cc,pgmpy,coronalabs,pexpect,company-mode,xmppjs,lanl,flowplayer,contiamo,jivesoftware,ceres-solver,Adobe-CEP,PlayFab,sektioneins,OpenSC,laravelio,STEllAR-GROUP,osmdroid,theupdateframework,apitrace,eset,ocsigen,nebula-plugins,bmob,Digilent,loomio,project-open-data,PolymerLabs,freecores,airbrake,VentureCraft,AnySoftKeyboard,sunlightlabs,binaryjs,bigspaceship,rdkit,ZBar,finagle,projectatomic,nfephp-org,hotosm,rocker-org,OfflineIMAP,vim-jp,glyptodon,linux-test-project,sutoiku,OneDrive,mobomo,moove-it,bpython,equinor,Piwigo,subsurface,constabulary,e-maxx-eng,appleseedhq,wilkelab,Warzone2100,Idean,Nitrux,wallarm,Nebo15,hipache,erxes,immobiliare,TDAmeritrade,attr-encrypted,brack3t,bitcraze,docker-java,IgniteUI,gocql,raspberrypilearning,teracyhq,globalize,acani,digidem,Differential,misoproject,cdglabs,zopefoundation,percolatestudio,veliovgroup,2240,razorpay,protobuf-c,mwaylabs,fastly,storesafe,asciidwango,box-project,Vonage,MLH,pivotal-cf,xolvio,ShareKit}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 32

wget 'https://api.github.com/search/repositories?q=org:'{radiant,postgis,SimpleSoftwareIO,tapharmonic,JackTeam,mpld3,dflydev,CN-Chrome-DevTools,DeemOpen,pyannote,tedious,vowsjs,symfony-cmf,openmrs,mulesoft-labs,linux-sunxi,Komodo,amplitude,cloudant,lanayotech,FarmBot,publiclab,tvheadend,incanter,ustclug,libbitcoin,geddy,drivendataorg,pololu,stackforge,YunoHost,urbanairship,rumpkernel,SegmentFault,VisualComputingInstitute,nytlabs,slate,prismicio,redsolution,BlueBrain,ratpack,OpenXRay,CERT-Polska,ghostery,boot-clj,rubygarage,hwi,biocore,omniti-labs,firebug,openjournals,TargetProcess,appunite,postmates,bustoutsolutions,hexpm,uwescience,spacenation,producthunt,aptly-dev,outbrain,CyberAgent,modxcms,genomicsclass,lfe,FNA-XNA,folkloreinc,adobe-photoshop,mate-desktop,sclorg,valhalla,RosettaCommons,mdgspace,chartbeat-labs,fslaborg,VoltDB,opentrack,Airtable,rgeo,mysociety,origamitower,DjangoGirls,WebBluetoothCG,Battelle,bibanon,AdaCore,pinguo,mathics,twitter-forks,mindsnacks,agoragames,themosis,sdslabs,silinternational,embulk,DevTips,as-ideas,lucidworks,structurizr,FFTW}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 33

wget 'https://api.github.com/search/repositories?q=org:'{littlstar,ocamllabs,nucleic,imweb,LunarG,otalk,modularscale,Mirantis,honeynet,criteo,jgrapht,js2coffee,rpush,bazaarvoice,pinry,inveniosoftware,Sitecore,ioquake,ehcache,KKBOX,searchbox-io,washingtonpost,typesafehub,objccn,initialstate,0ad,coralproject,idris-hackers,deephacks,lumapps,AugurProject,TKJElectronics,SpigotMC,u-boot,lxml,GlowstoneMC,RobotWebTools,Blazemeter,nanoc,plivo,f2etw,interactivethings,tasks,uclnlp,DHTMLX,EasyEngine,ApiGen,meitu,sulu,yougov,hammerlab,cpp-netlib,kartoza,itmuch,Telerik-Verified-Plugins,pothosware,Pixabay,twoscoops,podio,FormstoneClassic,datamapper,fiduswriter,phpservermon,auto-complete,laravel-china,frakbot,NoRedInk,globalsign,CESNET,leaflet-extras,concurrencykit,nose-devs,ChicagoBoss,alpinelinux,hivemq,Real-Serious-Games,klee,MatchbookLab,django-ckeditor,webRTC-io,FrozenNode,wine-mirror,programa-stic,Indatus,silexlabs,openxc,libtom,larvalabs,topfreegames,typeplate,rsyslog,aptana,nanobox-io,pwnieexpress,FRiCKLE,tech-srl,mathquill,rathena,algaworks,aftertheflood}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 34

wget 'https://api.github.com/search/repositories?q=org:'{dataliterate,asterisk,phpmd,InvoicePlane,node-app,orobix,starkandwayne,SpiderOak,iriscouch,BKWLD,Clever,Avocarrot,sandialabs,openenergymonitor,runtimejs,Maluuba,ligershark,todogroup,feedjira,codecasts,Sage,DFRobot,pallet,qTip2,stumpwm,WinVector,lift,commerceguys,berkshelf,0xd4d,hubot-scripts,LimeSurvey,riolet,Exa-Networks,aserg-ufmg,BedrockStreaming,itead,biokoda,ffi,django-nonrel,pganalyze,CGCookie,Datomic,schrodinger,rubyworks,PiranhaCMS,OpenELEC,BinaryAnalysisPlatform,littleosbook,ispc,oVirt,circleci,vazco,RiotGames,AcalephStorage,HotswapProjects,datalust,pgjdbc,Flotype,Meetic,modelmapper,shouldjs,ender-js,PGYER,phonegap-build,macadmins,openconfig,wantedly,jcabi,open-mpi,fluentribbon,blackmagic-debug,Brightify,ucsb-seclab,RedBearLab,microjs,smarty-php,openemr,adlnet,corelan,anjuke,Capgemini,spmjs,r-dbi,SciTools,ninjaframework,Fullscreen,FastReports,DotNetOpenAuth,Peer5,strophe,Smile-SA,DozerMapper,wojodesign,go-qml,unetbootin,wq,FancyPixel,sprache,Asymmetrik}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 35

wget 'https://api.github.com/search/repositories?q=org:'{go-python,sass-mq,Paperspace,bpkg,mashery,sapo,alliedmodders,connectbot,MacRuby,wet-boew,jmxtrans,tower,DynamoDS,zillow,marvinlabs,papertrail,underscoreio,stamen,opauth,learn-co-curriculum,teeworlds,project-imas,coreboot,there4,scipr-lab,odpf,jphp-group,kissjs,pixiv,phpbb,dwavesystems,kottans,Slicer,tradle,torodb,tessel,erlware,LiveHelperChat,be-fe,NVISOsecurity,html5blank,secure-software-engineering,WomenWhoCode,DemocracyOS,luster-io,znc,AmpersandJS,tarent,conformal,litaio,pyqt,zedapp,huboard,drupal-composer,fightforthefuture,nordnet,volojs,IOActive,opentripplanner,griffithlab,ruby-prof,gkajs,adobe-type-tools,sajari,RestyaPlatform,aqlaboratory,loov,Lab41,Bumblebee-Project,jakejs,CodementorIO,vim-ruby,sq,open-keychain,imagej,TestStack,cryptocoinjs,LunarLogic,gh-unit,kiibohd,wiredtiger,rubyconfig,openssh,cmangos,sharpdx,Hextris,diy,iluminar,qpdf,FreeRADIUS,BetterJS,Lickability,quantifiedcode,superherojs,georust,alestic,x-tag,gojp,wallstreetcn,invenia}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 36

wget 'https://api.github.com/search/repositories?q=org:'{marytts,Adobe-Marketing-Cloud,QuickBlox,linkeddata,Operational-Transformation,flightaware,ging,Squarespace,crawl,zfcampus,openconnect,git-cola,meteoric,protonet,infochimps-labs,common-workflow-language,simbody,ministryofjustice,citp,2359media,photo,developerforce,NEventStore,dresden-elektronik,codetriage,protegeproject,roomorama,materialsproject,hamstergem,livingsocial,webbukkit,SitePen,cc65,moodlehq,9elements,DNSPod,betagouv,LINCnil,BroadleafCommerce,JuliaWeb,kayak,NLua,caffeinated,i2p,boostcon,TiddlyWiki,denosaurs,emsec,Dynatrace,Syomus,protostuff,overshare,iipc,reduxframework,dionach,scalikejdbc,cloudbase,dino,getsling,embree,Ettercap,apigee-127,HackathonHackers,opentx,veandco,scummvm,racker,digiaonline,bazil,QuantBox,Spomky-Labs,getkirby-v2,transferwise,graphistry,viewfinderco,Codeux-Software,lukalabs,fizzed,bundestag,brightcove,notepadqq,dddinphp,bither,loresoft,compose,joosthub,OCamlPro,gnustep,intentkit,iosphere,reviewboard,xanzy,arcadia-unity,kindsoft,alleyinteractive,discoproject,jline,OryxProject,Zenika,code-mancers}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 40

wget 'https://api.github.com/search/repositories?q=org:'{datejs,arquillian,kiwix,openstenoproject,moses-smt,mailvelope,git-tfs,subgraph,jnr,saucelabs,catarse,BrightcoveOS,IdleHandsApps,rambler-digital-solutions,dateutil,trakt,esa,hechoendrupal,ququplay,Floobits,node-gh,cherrypy,publify,tinyspeck,space150,sikuli,Cycling74,leo-project,DFHack,backbone-paginator,bminor,hoteltonight,rakudo,9fans,lighttransport,get-iplayer,owtf,scribd,mitmedialab,SC5,ebu,CCExtractor,SWI-Prolog,kairosdb,Elgg,appdotnet,tuenti,oneclick,uniVocity,htty,planetlabs,eProsima,eldarion,BlueSpire,ConSol,bitlabstudio,mitreid-connect,RestComm,OpenBankProject,2ndQuadrant,StamusNetworks,nsubstitute,heroku-examples,mollie,lubuntu-dev,substantial,a16z,zilverline,KnightOS,kamailio,neo4jrb,websocket-rails,goburrow,datawire,WhichBrowser,circus-tent,Teamwork,Softmotions,log2timeline,mysensors,example42,justintv,vyos,WorksApplications,kokkos,libarchive,akeneo,featurist,snes9xgit,ACINQ,C2FO,whiteoctober,nullsecuritynet,komoot,unknown-horizons,stagemonitor,groundworkcss,UiPath,omniscientjs,opengeospatial}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 41

wget 'https://api.github.com/search/repositories?q=org:'{scorelab,Kunena,TTLabs,runtimeverification,cuthbertLab,AirenSoft,fedora-infra,VirtoCommerce,Calysto,das-labor,glassechidna,mongomapper,renderedtext,hipchat,eficode,osmocom,monitoringsucks,elninotech,nitroshare,cheekybits,aigamedev,Pathgather,iiitv,h5py,mistio,PureMVC,riptano,wiztools,scotty-web,Nextdoor,softonic,pupil-labs,dreamfactorysoftware,n0tr00t,phoronix-test-suite,Wiredcraft,ANXS,dedis,flyingsaucerproject,csmith-project,sphinxsearch,projectmesa,bigcompany,chardet,poise,USEPA,irontec,Go-zh,customink,JACoders,Appsilon,MidnightCommander,variety,ganglia,lab2023,nispok,funbox,Corvusoft,SELinuxProject,Huawei,CodeSleeve,python-rope,tunnelvisionlabs,bintray,datacenter,getqujing,avocode,SchemaStore,RetroShare,SmartBear,indeedeng,DbUp,buildroot,brainspec,SnowdogApps,trueinteractions,UniversalDependencies,spacetelescope,Logitech,p6spy,sabnzbd,python-diamond,dlab-berkeley,sismics,Aegisub,KitSprout,InstantWebP2P,AllenInstitute,MeetMe,haproxytech,jstat,datacarpentry,crowdint,usds,shouldly,brmson,libpnet,shiguredo,proj4js,sporkrb}'&page='{1..20} --waitretry=60 --retry-on-http-error=403 --wait 5 --tries 10

# Page 42
